apiVersion: v1
kind: Pod
metadata: 
  name: dev-pod
  labels:
    app: dev
    tier: kj
spec:
  containers:
  - name: dev
    image: redis
    env:
    - name: dev
      value: kj
    - name: dj
      value: kj