apiVersion: v1
kind: Pod
metadata:
  name: dev-test
  labels:
    app: nginx
    tier: dev
spec:
  containers:
  - name: dev-container
    image: nginx
    env:
    - name: dev
      value: "hello"
    - name: keshav
      value: "bye"
